# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 16:39
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('loginregistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('create', django.db.models.manager.Manager()),
            ],
        ),
    ]
