# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 21:56
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('loginregistration', '0002_auto_20160813_1039'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('login', django.db.models.manager.Manager()),
            ],
        ),
    ]
